# Generated by Django 5.0 on 2023-12-08 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myFeeds', models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], max_length=10, null=True)),
                ('otherFeeds', models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], max_length=10, null=True)),
                ('tagging', models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], max_length=10, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting', to='userprofile.profile')),
            ],
        ),
    ]
