# Generated by Django 5.0 on 2023-12-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='myFeeds',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='otherFeeds',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tagging',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10, null=True),
        ),
    ]
