# Generated by Django 5.0 on 2023-12-08 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_settings_myfeeds_alter_settings_otherfeeds_and_more'),
        ('userprofile', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setting', to='userprofile.profile'),
        ),
    ]
